### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by ashinzekene** [TrishaChetani/reactwithapi#1]
1. By convention, your render method should be the last method in a react component
https://github.com/TrishaChetani/reactwithapi/blob/a385437b626abfaef31c0e96bad4d96dad3f0bcb/src/App.js#L6

2. You should remove this else, you would be creating a new contact everytime the component mounts.
https://github.com/TrishaChetani/reactwithapi/blob/master/src/App.js#L43

3. I don't think you are using this
https://github.com/TrishaChetani/reactwithapi/blob/master/src/components/createcontact.js#L12

Apart from the issues above, your code looks good 👍

**Comment by TrishaChetani** [comment]
Thank you resolved the issue
